package com.spring.wefit.command;

import java.util.Date;

public class NoticeReplyVO {
	
	/* CREATE TABLE "SPRINGWEFIT"."NOTICEREPLY" 
	   (	"NRNUM" NUMBER(10,0) NOT NULL ENABLE, 
		"NBNUM" NUMBER(10,0) NOT NULL ENABLE, 
		"NRCONTENT" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		"MNUM" NUMBER(20,0) NOT NULL ENABLE, 
		"NRREGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
		 CONSTRAINT "PK_NOTICEREPLY" PRIMARY KEY ("NRNUM")
	  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM"  ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM" ;*/
	
	private int NRNUM;
	private int NBNUM;
	private String NRCONTENT;
	private int MEMBERNUM;
	private Date NRREGDATE;
	
	public int getNRNUM() {
		return NRNUM;
	}
	public void setNRNUM(int nRNUM) {
		NRNUM = nRNUM;
	}
	public int getNBNUM() {
		return NBNUM;
	}
	public void setNBNUM(int nBNUM) {
		NBNUM = nBNUM;
	}
	public String getNRCONTENT() {
		return NRCONTENT;
	}
	public void setNRCONTENT(String nRCONTENT) {
		NRCONTENT = nRCONTENT;
	}
	public int getMNUM() {
		return MEMBERNUM;
	}
	public void setMNUM(int memberNUM) {
		MEMBERNUM = memberNUM;
	}
	public Date getNRREGDATE() {
		return NRREGDATE;
	}
	public void setNRREGDATE(Date nRREGDATE) {
		NRREGDATE = nRREGDATE;
	}
	
	
	

}
